In [2]:
# ============================
# Random Forest Training Script
# ============================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import joblib

# ---------------------------------------
# 1. Load cleaned dataset
# ---------------------------------------
df = pd.read_csv("D:\Major Project\XGBoost\Dataset\Cleaned_GPS_Spoofing_Dataset.csv")

# ---------------------------------------
# 2. Select the same 10 features
# ---------------------------------------
selected_features = ['TOW', 'PD', 'RX', 'TCD', 'CP', 'DO', 'PRN', 'CN0', 'PC', 'EC']

X = df[selected_features]
y = df["Output"]

# ---------------------------------------
# 3. Load the same scaler used everywhere
# ---------------------------------------
scaler = joblib.load("../step02_Preprocessing/scaler.joblib")
X_scaled = scaler.transform(X)

# ---------------------------------------
# 4. Train/test split
# ---------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# ---------------------------------------
# 5. Class weights to handle imbalance
# ---------------------------------------
class_weights = {
    0: 1.0,
    1: 12.0,
    2: 14.0,
    3: 15.0
}

# ---------------------------------------
# 6. Train Random Forest model
# ---------------------------------------
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    class_weight=class_weights,
    random_state=42,
    n_jobs=-1,
)

rf_model.fit(X_train, y_train)

# ---------------------------------------
# 7. Predictions
# ---------------------------------------
y_pred = rf_model.predict(X_test)

# ---------------------------------------
# 8. Evaluation
# ---------------------------------------
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# ---------------------------------------
# 9. Save model
# ---------------------------------------
joblib.dump(rf_model, "rf_model.joblib")
print("\nModel saved as rf_model.joblib")


Accuracy: 0.905745010087556

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.95      0.95     79565
           1       0.78      0.78      0.78      7292
           2       0.61      0.60      0.61      8846
           3       0.92      0.92      0.92      6403

    accuracy                           0.91    102106
   macro avg       0.81      0.81      0.81    102106
weighted avg       0.91      0.91      0.91    102106


Confusion Matrix:
 [[75580   837  2642   506]
 [  887  5670   735     0]
 [ 2746   786  5314     0]
 [  485     0     0  5918]]

Model saved as rf_model.joblib
